### ISSUE TITLE
Missing tones in CANYON.MID due to odd bank number

### ISSUE THREAD

**Issue by kode54** [nukeykt/Nuked-SC55#7]
CANYON.MID appears to be missing the piano instrument due to using a weird bank number. Maybe this is a known issue with the SC55-mkII?

**Comment by Karmeck** [comment]
Maybe an issue with the file itself.

A thread on the issue and how the mkII handles it:
https://www.vogons.org/viewtopic.php?t=81379

**Comment by Falcosoft** [comment]
Yes, as Karmeck mentioned you must have the version of CANYON.MID that sets bank MSB 5 + Bank LSB 87 + Program 90 to channel 1. Since the mkII has no Capital Tone Fallback feature it remains silent on channels where invalid  bank + program combination is found.
The easiest way to cure this problem is to send a GM reset SysEx message before playing such files. This emulator seems to support GM reset the same way as the real unit.

**Comment by nukeykt** [comment]
yes, this behavior is consistent with real hardware
